[build]
  command = "npm run build"
  publish = ".next"

# Enable build caching for faster rebuilds
[[cache]]
  path = ".next/cache"

[[cache]]
  path = "node_modules/.cache"

# Handle Next.js API routes and dynamic routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle all other routes for Next.js SPA
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200


# Headers for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = ".public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"